dist: xenial
language: cpp
os: linux

git:
  depth: 1

matrix:
  include:
    - env: BUILD_TYPE=CRLF
    - env: BUILD_TYPE=validate
      addons:
        apt:
          packages:
            - libxml2-utils
    - env: BUILD_TYPE=generate GCC_VERSION=9
      addons: &gcc9
        apt:
          packages:
            - g++-9
          sources:
            - ubuntu-toolchain-r-test
    - env: BUILD_TYPE=generate CLANG_VERSION=9
      addons: &clang9
        apt:
          packages:
            - clang-9
            - libstdc++-9-dev
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - env: BUILD_TYPE=make CXX=g++-9
      addons: *gcc9
    - env: BUILD_TYPE=make CXX=clang++-9
      addons: *clang9

script:
  - |
    case "$BUILD_TYPE" in
      (CRLF)
        echo "Checking for carriage returns..."
        if grep -IUrl --exclude-dir=.git . -e $'\r'; then
          echo "Sorry, carriage returns are not allowed in the repo."
          exit 1
        else
          echo "All good."
        fi
        ;;
      (generate)
        if [ -n "$GCC_VERSION" ]; then
          export CXX=g++-${GCC_VERSION}
        elif [ -n "$CLANG_VERSION" ]; then
          export CXX=clang++-${CLANG_VERSION}
        fi
        echo "Building generator..."
        bash -ex ./bin/build_pgms.sh || exit 1
        echo "Generating lists..."
        mkdir mailing && bash -ex ./bin/build_lists_only.sh || exit 1
        ;;
      (make)
        touch meta-data/dates # this is too slow to generate
        make lists -j4 CXX=$CXX
        ;;
      (validate)
        for i in xml/issue*.xml ; do
          xmllint --noout --nowarning --dtdvalid xml/lwg-issue.dtd $i
        done
        ;;
    esac
